### ISSUE TITLE
Images are not being transformed into figures

### ISSUE THREAD

**Issue by Bernardo-MG** [Bernardo-MG/docs-maven-skin#11]
The skin is meant to transform the images on the main section into figures, which will have the alternate text as the figure caption, but this is not happening, and instead the img element by itself is being used.

**Comment by Bernardo-MG** [comment]
This is an error caused by the helping tools.

**Comment by Bernardo-MG** [comment]
The updated Maven Site fixer tools now handle this correctly.

**Comment by vspiliop** [comment]
Isn't the purpose of image alt test to be displayed in case the image is not available? Why add by default such a fig caption?

**Comment by Bernardo-MG** [comment]
It's just because I see an ambiguity when transforming from Markdown to HTML. In markdown you just add a name to the image, but for the Maven site you need the alternate name for accessibility issues. As I can't get an alternative name from anywhere, this ends with a redundant alt. Additionally, the title adds a popup to the image, which will also look redundant.

**Comment by Bernardo-MG** [comment]
The alternative as you say is removing the figures and using just images. Actually I don't remember why I used them, as I made this part of the skin years ago.
