### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by JohnnyCosta** [Bernardo-MG/docs-maven-skin#136]
I added to my project and receive back this:
Error during page generation: Error while generating code. Unable to find resource 'site-macros.vm' -> [Help 1]

- site.xml was copy from samples.
- plugin:
```
<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-site-plugin</artifactId>
						<version>3.3</version>
						<dependencies>
							<dependency>
								<groupId>org.apache.velocity</groupId>
								<artifactId>velocity</artifactId>
								<version>1.7</version>
							</dependency>
						</dependencies>
						<executions>
					</plugin>
```

**Comment by Bernardo-MG** [comment]
With the latest versions of the Maven Site plugin you no longer need to add Velocity 1.7 as a dependency.

Something like this is enough:

```
<plugin>
   <!-- Site -->
   <!-- Generates the Maven Site -->
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-site-plugin</artifactId>
   <dependencies>
      <dependency>
         <!-- Docs Maven Skin -->
         <groupId>com.bernardomg.maven.skins</groupId>
         <artifactId>docs-maven-skin</artifactId>
         <version>${site.skin.version}</version>
      </dependency>
   </dependencies>
</plugin>
```

Adding the skin as a dependency inside the plugin also reduces the dependency scope. It will be available only to the plugin.

**Comment by Bernardo-MG** [comment]
There was no confirmation, but the skin has been verified to work correctly. I'm closing this.
