### ISSUE TITLE
Template customization

### ISSUE THREAD

**Issue by Jeff-Walker** [Bernardo-MG/docs-maven-skin#138]
Is there a way to customize the template a bit at site generation time?

I want to add a snippet of javascript to make the highlight.js render for my code blocks. My code blocks aren't like what highlight.js expects.

```javascript
hljs.configure({useBR: true});

$('div pre.source').each(function(i, block) {
  hljs.highlightBlock(block);
});
```
I've not been able to find a way to make doxia include arbitrary markup for the browser.

**Comment by Bernardo-MG** [comment]
Currently highligh.js is being initialized by adding this line to the footer:

```
<script>hljs.initHighlightingOnLoad();</script>
```

This change would require adding a way to override this line. I'll take a look at it.

It may be a good idea adding some way to change the included version of highlight. As it requires configuration the library is not being added dynamically.

**Comment by Bernardo-MG** [comment]
Added issues #139 and #140.

**Comment by Bernardo-MG** [comment]
I've just published v1.3.0.

The highlight.js initialization code was moved into a file located at js/initializeHighlight.js, which can be overriden.

For this create a file located in the following path and add your own initialization code inside:

```
src/site/resources/js/initializeHighlight.js
```

The default initialization code is:

```
$(document).ready(function() {

   // Uses the default initialization
   hljs.initHighlightingOnLoad();

});
```

Tell me if this is works.

**Comment by Jeff-Walker** [comment]
This is working just fine. Thanks for your quick response.

Also, do you have a CSS file you read from src/site ? I can include it in the js file if I need to.

**Comment by Bernardo-MG** [comment]
The CSS file is read from the /css/style.min.css file. If you need to add custom CSS I can add a file meant for being overriden, like the highlight one.

**Comment by Bernardo-MG** [comment]
I've added support to add custom CSS and JS files:

```
<custom>
   <skinConfig>
      <customStyle>./css/custom.css</customStyle>
      <customScript>./js/custom.js</customScript>
   </skinConfig>
</custom>
```

If you need you can use them.

Also, all these changes are commented in the documentation.

I'm closing this issue.

**Comment by Jeff-Walker** [comment]
This is awesome. Thanks for your help.
