### ISSUE TITLE
Thoughts about generated anchors

### ISSUE THREAD

**Issue by SR-G** [Bernardo-MG/docs-maven-skin#162]
Hello,

I'm really starting to use extensively this skin, and i wonder if you would have any idea about table of contents (it's not a bug).

Indeed i'm using VSCode to automatically generate the table of contents of my .md files (otherwise it's way too cumbersome to do that by hand), and the generated anchors are not the same than the ones generated by docs-maven-skin.

For example, [VSCode Markdown-All-in-One plugin](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) is generating a link on '#My-Title' (for a `## My Title` markdown title) (through the `CTRL+SHIFT+P` > `Create Table of Contents feature`), whereas the anchor generated by docs-maven-skin is '#mytitle' .

Would there be any simple solution allowing to reconciliate the two ?

**Comment by Bernardo-MG** [comment]
I think they are generated automatically through Doxia when building the HTML from markdown or any other source.

I'll take a look and check for any possible way to handle this.

**Comment by Bernardo-MG** [comment]
I've located where the anchor ids are being generated. It's this line:

```
#**##set( $empty = $siteTool.fixHeadingIds($bodyContentParsed) )
```

This tool comes from https://github.com/Bernardo-MG/maven-site-fixer

I'll take a look and see what can be done.

**Comment by Bernardo-MG** [comment]
About valid formats for the id attribute: https://mathiasbynens.be/notes/html5-id-class

In HTML5 the id attribute may have any value, as long as it isn't empty. Now I would like to find some style guide for ids, or some common pattern for it, if that exists.

**Comment by Bernardo-MG** [comment]
@SR-G I got some time to change how the internal anchor ids are generated.

Could you try if this helps you? It's v1.4.3

**Comment by SR-G** [comment]
@Bernardo-MG Sorry for delay, only had the opportunity to test this out today. Seems 

way better now at first glance, thanks for the modification - i just still have issues with special characters, like chapters' titles containing double-quotes or question mark.

For example a title like : 'What is the lifecycle ?'
Leads to 
- a link in the toc with `<a href="#what-is-the-lifecycle">`
- an anchor with `<h3 id="what-is-the-lifecycle-?">What is the lifecycle ?</h3>`
(= special characters not being consistent in the two situations)

Hence the non-working link.

**Comment by Bernardo-MG** [comment]
Removing special characters from the link id would be a good option? Seems to be the best, and easiest, way to tackle this.

**Comment by SR-G** [comment]
On my side it would be fine like this, indeed (and would alleviate the need to handle any form of encoding around these special characters, like the quotes).

**Comment by Bernardo-MG** [comment]
I've just released v1.4.4. Could you try it?

**Comment by SR-G** [comment]
Hey. Thanks. I will ! But could you just push the 1.4.4 version on the maven repo, like previous versions ? (right now only 1.4.3 is published : https://mvnrepository.com/artifact/com.bernardomg.maven.skins/docs-maven-skin)

**Comment by Bernardo-MG** [comment]
Done
