### ISSUE TITLE
project.scm.url

### ISSUE THREAD

**Issue by sirReeall** [Bernardo-MG/docs-maven-skin#165]
Hi,

I'm not sure if I have an incorrect configuration, but when I specific project.scm.url in my pom.xml file, the bottom and icon href becomes ./

You can see this in the following commits:

https://github.com/sirReeall/testing-maven-site-plugin/commit/e821b7b176093f4f43f45dcc39b1fefa95b44f10#diff-9302750b09f738721be4645dc0a75b4b

When I comment out project.scm.url in pom.xml, then the href becomes the value specified in site.xml.

Could you point me in the direction of where I am going wrong?

**Comment by Bernardo-MG** [comment]
I've just made a pull request into your projects, which seems to fix the problem.

I just changed the URL from:

> https://github.com/sirReeall/testing-maven-site-plugin

To

> https://www.github.com/sirReeall/testing-maven-site-plugin

Seems to be a problem in the plugin itself.

**Comment by Bernardo-MG** [comment]
I've been checking the tests, and your configuration should be working.

There is a test case which verifies that the Github icon is generated correctly for the following URL:

> https://github.com/Bernardo-MG/docs-maven-skin

**Comment by Bernardo-MG** [comment]
Also, just in case, I've generated the site using the following command:

> mvn clean verify site

**Comment by sirReeall** [comment]
Thanks for the assistance, adding www worked
