### ISSUE TITLE
Add option to use bg-dark instead of bg-light

### ISSUE THREAD

**Issue by okorz001** [Bernardo-MG/docs-maven-skin#201]
Most dark themes, e.g. darkly, look pretty bad right now because the header and footer are hardcoded to use the bg-light class. It would be nice to be able to use bg-dark (or bg-primary) instead.

**Comment by Bernardo-MG** [comment]
I've released the version 2.2.1 to handle this. Could you try it and tell me if it works for your needs?

To change the background you will need to set the shine property to dark, similar to this example:

```
<custom>
   <skinConfig>
      <bootswatchStyle>darkly</bootswatchStyle>
      <shine>dark</shine>
   </skinConfig>
</custom>
```

This is added into the site.xml file

**Comment by okorz001** [comment]
Wow, thanks for the quick response!

I noticed that you are using bg-primary on the navbar when shine=dark. This seems to work for some themes such as darkly and slate, but it still looks jarring on solar. Perhaps this bgshine should be configurable in the site.xml too? I also noticed that bgshine is not used in the footer, but I'm not sure if that was intentional or not. Ironically, this makes the footer (but not the navbar) look jarring on some themes like cyborg.

I think I will probably just use darkly with dark though, so this isn't a big deal for me.

**Comment by okorz001** [comment]
Technically a separate but related issue -- can you make the highlight.js theme configurable too? For example, darcula looks much better than default on the darkly bootswatch theme. I see that the highlight.js themes are already bundled.

**Comment by Bernardo-MG** [comment]
I'll take a look at the background color setting. I hope this weekend I'll have some time for it.

**Comment by Bernardo-MG** [comment]
I've just release version 2.2.2. It includes a new option to override the bg color:

```xml
<custom>
  <skinConfig>
    <!-- Use the sketchy style -->
    <bootswatchStyle>darkly</bootswatchStyle>
    <shine>dark</shine>
    <bgshine>dark</bgshine>
  </skinConfig>
</custom>
```

Could you try it?

**Comment by okorz001** [comment]
Thanks, this works great!
