### ISSUE TITLE
Anchors being removed in generated MOJO documentation

### ISSUE THREAD

**Issue by jamezp** [Bernardo-MG/docs-maven-skin#209]
The following removes all the `<a name="#someid">` elements from generated MOJO pages. 
https://github.com/Bernardo-MG/docs-maven-skin/blob/141f5ef3a4a18b11d7f48d71b86b0d3695601f12/src/main/resources/META-INF/maven/macros/setup-macros.vm#L71-L74

Generated documentation for maven plugin goals includes the parameters for the goal. On the upper portion of the page the parameters are listed with a link to the details about the parameter. Because of the above code snippet these links no longer work because the anchor from the parameter detail is removed.

The simple solution is to simply remove that rule. However, I assume it was placed there for a reason and the JavaDoc on the `Html5UpdateTool.removeNoHrefLinks` it says:

> Returns the result from removing links with no href attribute defined from the received element contents.
> These links are added by Doxia mainly to the headings. The idea seems to allow getting an internal anchor by clicking on a heading, but it does not work correctly on all skins (or maybe it is just missing something) making it invalid HTML code.
> Instead of just removing the links these will be actually unwrapped, keeping any text they may contain.

If there is something I missed on a way to disable this please just let me know :)

**Comment by Bernardo-MG** [comment]
Thanks. I think next week I'll have time to look at this.

**Comment by Bernardo-MG** [comment]
I've just published v2.2.5 and tried on your project. It works.

I don't see any trouble with the change, apart from the HTML validator giving a warning due to it being an obsolete usage of the anchor tag.

Try it and tell me how it goes.

**Comment by jamezp** [comment]
Awesome thanks @Bernardo-MG. I appreciate the quick response and the wonderful skin :)

One minor thing I noticed is, at least on Chrome, the ID's seem to be case sensitive. On the links something like `authenticationConfig` is transformed to:
```
<a href="#authenticationconfig">authenticationConfig</a>
```
Note the lower case. The reference name is:
```
<a name="authenticationConfig">authenticationConfig</a>:
```

Note the `name` attribute keeps the capital "C".

**Comment by Bernardo-MG** [comment]
@jamezp I've release v2.2.6, which changed how ids are handled. Can you try it?

**Comment by jamezp** [comment]
@Bernardo-MG Works perfectly! Thank you!

**Comment by Bernardo-MG** [comment]
Great. I'm closing the issue then. Sorry it took so long.
